api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import ItemsViewSet, BuyViewSet

router = routers.DefaultRouter()
router.register(r'item', ItemsViewSet)
router.register(r'^buy/(?P<item_id>\d+)', BuyViewSet, basename='buy_item')

urlpatterns = [
    path('', include(router.urls))
]

pay/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pay_app.urls', namespace='pay_app')),
    path('api/v1/', include('api.urls')),
]

pay_app/urls.py
from django.urls import path
from . import views


app_name = 'pay_app'

urlpatterns = [
    path('item/', views.shop_all_items, name='items'),
    path('buy/<int:item_id>/', views.buy, name='buy'),
    path('item/<int:item_id>/', views.item, name='item_detail'),
]

pay_app/models.py
from django.db import models


class Item(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name='Наименование товара'
    )
    description = models.CharField(
        max_length=500,
        verbose_name='Описание и характеристики товара'
    )
    price = models.FloatField(
        verbose_name='Цена'
    )

    def __str__(self):
        return self.name

api/views.py
from rest_framework import viewsets, views, status
from django.shortcuts import get_object_or_404, redirect

from pay_app.models import Item
from pay_app.create_price import create_product

from .serializers import ItemSerializer


class ItemsViewSet(viewsets.ModelViewSet):
    """Все товары."""
    queryset = Item.objects.all()
    serializer_class = ItemSerializer


class BuyViewSet(viewsets.ViewSetMixin):
    """Покупка товара."""

    def get(self, pk):
        item = get_object_or_404(Item, id=pk)
        session = create_product(item)
        return redirect(session.url, status=status.HTTP_200_OK)

pay_app/views.py
from django.shortcuts import redirect, render
from .models import Item
from .create_price import create_product


def shop_all_items(request):
    items = Item.objects.all()
    context = {
        'items': items,
    }
    template = 'pay_app/all_items.html'
    return render(request, template, context)


def buy(request, item_id):
    item = Item.objects.get(id=item_id)
    session = create_product(item)
    return redirect(session.url)


def item(request, item_id):
    item = Item.objects.get(id=item_id)
    context = {
        'item': item,
    }
    template = 'pay_app/item.html'
    return render(request, template, context)

templates/pay_app/all_items.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Наши товары</h1>
    {% csrf_token %}
    {% for item in items %}
    <h3>{{ item.name }}</h3>
    <ul>
        <li>Наименование: {{ item.name }}</li>
        <li>Описание товара: {{ item.description }}</li>
        <li>Цена: {{ item.price }} $</li><br>
        <button onclick=location.href="{% url 'pay_app:item' item.id %}" id="buy-button">Узнать подробности</button>
    </ul><hr><br>
    {% endfor %}
</body>
</html>

templates/pay_app/item.html
<html>
  <head>
    <title>Buy Item 1</title>
  </head>
  <body>
    <h1>{{ item.name }}</h1>
    <p>{{ item.description | title }}</p>
    <p>{{ item.price }} $</p>
    <button onclick=location.href="{% url 'pay_app:buy' item.id %}" id="buy-button">Buy</button>
    <script type="text/javascript">
      var stripe = Stripe('pk_test_a9nwZVa5O7b0xz3lxl318KSU00x1L9ZWsF');
      var buyButton = document.getElementById(buy-button');
      buyButton.addEventListener('click', function() {
        // Create a new Checkout Session using the server-side endpoint
        // Redirect to Stripe Session Checkout
        fetch('/buy/1', {method: 'GET'})
        .then(response => return response.json())
        .then(session => stripe.redirectToCheckout({ sessionId: session.id }))
      });
    </script>
  </body>
</html>